name: Haxe CI

on:
  pull_request:
  push:
    paths:
      - src/**
      - test/**
      - haxelib.json

jobs:
  run_test_suite:
    strategy:
      matrix:
        # Version list: https://haxe.org/download/list/
        haxe-version: [ '4.1.5', '4.2.5', '4.3.1' ]
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Run the Test Suite
        run: haxe -cp src -cp test -main test.RunTests -resource test/snapshot-rev4.json@snapshot-rev4 --interp
