name: Haxe CI

on:
  push:
  workflow_dispatch:

jobs:
  run_test_suite:
    strategy:
      matrix:
        # Version list: https://haxe.org/download/list/
        haxe-version: [ '3.4.7', '4.1.5', '4.2.5', '4.3.7' ]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Run the Test Suite
        run: haxe -cp src -cp test -main test.RunTests -resource test/snapshot-rev4.json@snapshot-rev4 --interp
