name: Haxe CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0' # 3:00 AM every Sunday

jobs:
  run_test_suite:
    strategy:
      matrix:
        # Version list: https://haxe.org/download/list/
        haxe-version: [ '3', '4.1', '4.2', '4.3' ]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Run the Test Suite
        run: haxe -cp src -cp test -main test.RunTests -resource test/snapshot-rev4.json@snapshot-rev4 --interp
